name: Build
permissions:
    contents: read
on:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOMAIN: localhost
      ENVIRONMENT: test
      GAME_NODE_NAME: node-1
      GAME_NODE_SOCKET_IO_PORT: 9500
      HTTPS: false
      LOBBY_PORT: 4000
      LOBBY_WS_URL: ws://127.0.0.1:6000
      SECRET: testsecret

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '26'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript compile
        run: npx tsc -p tsconfig.test.json

      - name: Fetch card data
        run: node bin/fetchdata.js prod

      - name: Test
        run: npx jasmine
        env:
          JASMINE_CONFIG_PATH: ./jasmine.json

      - name: Lint
        run: npm run lint
